### ISSUE TITLE
How to expiry cache

### ISSUE THREAD

**Issue by learnwithgabbar** [contentstack/contentstack-swift#11]
If you pass cache type `.cacheElseNetwork` to the content stack, then it will return the data from the cache, not from the network. 
that work fine.

case:- 
1. The app uses cache policy to the entity `.cacheElseNetwork` 
2. The content stack manager republishes the entity after making changes.
3. App gets the old data due to the cache policy implemented.

How  to expiry the cache when Entity is republished.

**Comment by ishaileshmishra** [comment]
Hi, @ajjumehra Thanks for writing us. Currently, SDK does not offer a feature for verifying published data and subsequently purging the cache on the client side. As part of our caching strategy, data is retained in the cache for the standard duration which is provided by default URLSession.

@uttamukkoji

**Comment by learnwithgabbar** [comment]
@uttamukkoji 
Any new progress in the area of caching the content, as soon the content  grows the cache is quickly removed from the URLSession

**Comment by ishaileshmishra** [comment]
We have not made any progress on the mentioned issue. Furthermore, in case of any help please contact support@contentstack.com

@uttamukkoji @learnwithgabbar
