### ISSUE TITLE
Check if Any Entry is updated or not

### ISSUE THREAD

**Issue by aj-pilot** [contentstack/contentstack-swift#24]
is there a way to check when an entry has been updated recently?  suppose we have 20 entries in the content stack and want to know any of these is updated recently so that we can only fetch the recently updated entries instead of all

**Comment by ishaileshmishra** [comment]
Hi @aj-pilot, to determine the timing of the last entry modification, you can refer to the **updated_at** key in the response api is returning to you. If you require further assistance, please feel free to reach out to our customer support team.

**Comment by cs-raj** [comment]
Closing the issue as there was no further communication 
cc: @abhinav-from-contentstack @shafeeqd959 @netrajpatel
