### ISSUE TITLE
Bug when caching

### ISSUE THREAD

**Issue by Ricardo1980** [contentstack/contentstack-swift#8]
My app uses `URLCache.shared` to setup a global cache with 100 MB of memory, 250 MB of disk.

When using this library, I realised my caching was by far less effective than usual.
After some research, I found what in my opinion is a bug.

In this file:
https://github.com/contentstack/contentstack-swift/blob/88e2c4d901e7f0bc1ab512d619e0d0d7d42e0897/Sources/Stack.swift#L83

We have:
`URLCache.shared = CSURLCache.default`

Which is affecting the entire app.

The reason my app is not working as good as I expected is because the cache you are setting (I remark, globally) uses this configuration:

`internal static let `default`: CSURLCache = CSURLCache(memoryCapacity: 1024 * 1024, diskCapacity: (1024 * 1024 * 5), diskPath: "csio_cache")`
https://github.com/contentstack/contentstack-swift/blob/db6ab5f969f0060f4955d735602fac737a3ca390/Sources/CSURLCache.swift#L12

That's 1 MB of memory cache and 10 MB of disk cache, Basically, nothing.
I don't know if that is appropriate for ContentStack or not, but for sure it is not appropriate for other parts of my app.

So, instead of replacing the global `URLCache`, can you do in your code some like this in the Stack initialiser?:
`self.config.sessionConfiguration.urlCache = CSURLCache.default`

Doing that, you have your own `URLCache` without affecting other parts of the apps that are using your library.

If you want a PR, let me know, I can do it.

Thanks a lot.

**Comment by ishaileshmishra** [comment]
Thanks for raising the issue, We are looking into the issue. Meanwhile, you can raise PR @Ricardo1980

**Comment by ajjumehra** [comment]
Any Update on this

**Comment by uttamukkoji** [comment]
Hi @ajjumehra,

We have resolved the `URLCache` issue in v1.3.1. Closing this issue,  If you have any concern or issue you can re-open or create new issue.
