### ISSUE TITLE
Reference is coming in Form of Array instead a Dictionary 

### ISSUE THREAD

**Issue by ajjumehra** [contentstack/contentstack-swift#9]
`
{

    "entries": [
        {
            "_version": 11,
            "locale": "en-us",
            "uid": "bltad39906cf7c38164",
            "ACL": {},
            "_in_progress": false,
            "created_at": "2022-09-20T06:44:04.418Z",
            "created_by": "blt9b096dea849901c3",
            "tags": [],
            "test_data": [
                {
                    "uid": "blt6fffd87bd93d668a",
                    "_content_type_uid": "test_data"
                }
            ],
            "title": "Feature Reserve Parking",
            "updated_at": "2022-09-21T12:13:55.067Z",
            "updated_by": "blt9b096dea849901c3",
            "publish_details": {
                "environment": "blte8d75304cb393ab5",
                "locale": "en-us",
                "time": "2022-09-21T12:14:03.298Z",
                "user": "blt9b096dea849901c3"
            }
        }
    ]
}
`
**test_data** should be a dictionary instead of an array

`
  "test_data":  
    {
                    "uid": "blt6fffd87bd93d668a",
                    "_content_type_uid": "test_data"
    }
`

**Comment by uttamukkoji** [comment]
Hi @ajjumehra,

Thanks for raising issue. Can you please check the ContentType schema for the entry field `test_data` is of multiple type or it can refer to multiple ContentType.

As above response seems to be expected for us, we are closing issue. 

If you want more understanding about above scenario, please connect us to support@contentstack.com we will be happy to resolve your queries by connecting you.
